# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-02 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_tag', models.BooleanField(default=1)),
                ('last_modify_user_id', models.BigIntegerField(null=True)),
                ('create_user_id', models.BigIntegerField(null=True)),
            ],
        ),
    ]
