# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-02 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtilceClassify',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Base')),
                ('classify_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'xiaoshuo_classify',
            },
            bases=('app.base', models.Model),
        ),
    ]
