# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-05 03:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AticleArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_tag', models.BooleanField(default=1)),
                ('last_modify_user_id', models.BigIntegerField(null=True)),
                ('create_user_id', models.BigIntegerField(null=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('article_id', models.BigIntegerField()),
                ('sort', models.BigIntegerField(verbose_name=20)),
            ],
            options={
                'db_table': 'xiaoshuo_article',
            },
        ),
        migrations.CreateModel(
            name='AticleChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_tag', models.BooleanField(default=1)),
                ('last_modify_user_id', models.BigIntegerField(null=True)),
                ('create_user_id', models.BigIntegerField(null=True)),
                ('title', models.CharField(max_length=255)),
                ('num', models.BigIntegerField(verbose_name=20)),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.AticleAbout')),
            ],
            options={
                'db_table': 'xiaoshuo_chapter',
            },
        ),
        migrations.AddField(
            model_name='aticlearticle',
            name='parent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.AticleChapter'),
        ),
    ]
